#ifndef COMPAT_ABSL_BASE_ATTRIBUTES_H_
#define COMPAT_ABSL_BASE_ATTRIBUTES_H_

#define ABSL_ATTRIBUTE_ALWAYS_INLINE
#define ABSL_ATTRIBUTE_NOINLINE
#define ABSL_ATTRIBUTE_UNUSED
#define ABSL_MUST_USE_RESULT
#define ABSL_ATTRIBUTE_WARN_UNUSED
#define ABSL_DEPRECATED(message) [[deprecated(message)]]
#define ABSL_ATTRIBUTE_LIFETIME_BOUND
#define ABSL_ATTRIBUTE_PACKED __attribute__((packed))
#define ABSL_CONST_INIT

#endif
