#ifndef COMPAT_ABSL_BASE_NULLABILITY_H_
#define COMPAT_ABSL_BASE_NULLABILITY_H_

#define ABSL_NULLABILITY_COMPATIBLE
#define ABSL_NONNULL
#define ABSL_NULLABLE
#define ABSL_NULLABILITY_UNKNOWN

#endif
